cluster_endpoint                   = ""
cluster_certificate_authority_data = ""
oidc_provider_arn                  = ""
vpc_id                             = ""
private_subnets                    = ""
sso_admin_group_id                 = ""